@fhirUrl={{$dotenv FHIR_URL}}
GET http://localhost:7071/api/HttpExample?name=World

###
GET {{fhirUrl}}/metadata

###
GET {{fhirUrl}}/PractitionerRole
Authorization: {{$dotenv TOKEN}}

###
POST {{fhirUrl}}/$import
Prefer: respond-async
Content-Type: application/fhir+json
Authorization: {{$dotenv TOKEN}}

{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "inputFormat",
            "valueString": "application/fhir+ndjson"
        },
        {
            "name": "mode",
            "valueString": "IncrementalLoad"
        },         
        {
            "name": "input",
            "part": [
                { 
                    "name": "url",
                    "valueUri": "{{fhirUrl}}/data/2024-07-22 (1).ndjson"
                }
            ]
        }
    ]
}

###
GET {{fhirUrl}}/_operations/import/7
Authorization: {{$dotenv TOKEN}}
Accept: application/fhir+json
Content-Type: application/fhir+json

###
GET  https://ahdsjdf43tf5zcwks-api1.fhir.azurehealthcareapis.com/_operations/import/8
Authorization: {{$dotenv TOKEN}}